### ISSUE TITLE
Create own TestNet

### ISSUE THREAD

**Issue by AK315** [DeStream-dev/destream-blockchain#3]

**Comment by mbdestream** [comment]
1. Stratis source codes analysis to understand what part of Stratis is in charge for communication with network;
2. Reading available stratis documentations and searching information about testnet creation.

**Comment by mbdestream** [comment]
1. Node traffic analysis to figure out what remote addresses are used;
2. Node deployment on test server and tuning it, running;
3. Source codes research, rework code places to replace ip-addresses and dns-names with our test server ip and dns-addresses;
4. Traffic analysis to understand whether the local node communicates with test server node;

On current stage we have successfully connected local development node with test server node. But we have to figure out why the traffic between our nodes contains requests to unknown ip-addresses.

**Comment by AK315** [comment]
Now we have to introduce a new key in Node cli that will designate using of our DeStream TestNet

**Comment by mbdestream** [comment]
Cli is extended by adding new command line arguments:
1. "-destreamtest" to run node configured to connect with destream test node;
2. "-destreamtestserver" to run test server node.

**Comment by AK315** [comment]
OK. Implemented.
